import { supabase } from './supabaseClient'

const fields = 'id, supplier_id, name, category, description, price, unit, quantity_available, city, state, image_url, availability_status, created_at, updated_at'
const publicFields = 'id, name, category, description, price, unit, quantity_available, city, state, image_url, availability_status, created_at, updated_at'
function errorMessage(error, action = 'load') { if (error?.code === '42501') return new Error('You do not have permission to manage this material.'); if (error?.code === '23514') return new Error('One of the material values is invalid.'); return new Error(action === 'save' ? 'Unable to save your material. Please try again.' : 'Unable to load materials. Please try again.') }
export async function listMaterials(filters = {}) { let query = supabase.from('materials').select(publicFields).order(filters.sort === 'price' ? 'price' : 'created_at', { ascending: filters.sort === 'price' }); const search = (filters.search || '').replace(/[(),*]/g, ' ').replace(/\s+/g, ' ').trim(); if (search) query = query.or(`name.ilike.%${search}%,category.ilike.%${search}%,description.ilike.%${search}%,city.ilike.%${search}%,state.ilike.%${search}%`); if (filters.category) query = query.eq('category', filters.category); if (filters.city) query = query.eq('city', filters.city); if (filters.state) query = query.eq('state', filters.state); if (filters.availability) query = query.eq('availability_status', filters.availability); if (filters.minPrice) query = query.gte('price', Number(filters.minPrice)); if (filters.maxPrice) query = query.lte('price', Number(filters.maxPrice)); const { data, error } = await query; if (error) throw errorMessage(error); return data || [] }
export async function getMaterial(id) { const { data, error } = await supabase.from('materials').select(publicFields).eq('id', id).maybeSingle(); if (error) throw errorMessage(error); return data }
export async function getCurrentMaterialProfile(materialId) { const { data: userData, error: userError } = await supabase.auth.getUser(); if (userError || !userData.user) throw new Error('Authentication required'); const searchParams = new URLSearchParams(window.location.search); if (searchParams.get('new') === '1') return null; const listingId = materialId || searchParams.get('id'); let query = supabase.from('materials').select(fields).eq('supplier_id', userData.user.id); if (listingId) query = query.eq('id', listingId); else query = query.order('created_at', { ascending: false }).limit(1); const { data, error } = await query.maybeSingle(); if (error) throw errorMessage(error); return data }
export async function saveMaterial(material) { const { data: userData, error: userError } = await supabase.auth.getUser(); if (userError || !userData.user) throw new Error('Authentication required'); const payload = { ...material, supplier_id: userData.user.id, name: material.name.trim(), category: material.category.trim(), description: material.description.trim() || null, price: Number(material.price), unit: material.unit.trim(), quantity_available: Number(material.quantity_available), city: material.city.trim(), state: material.state.trim(), image_url: material.image_url?.trim() || null }; const query = material.id ? supabase.from('materials').update(payload).eq('id', material.id).eq('supplier_id', userData.user.id).select(fields).single() : supabase.from('materials').insert(payload).select(fields).single(); const { data, error } = await query; if (error) throw errorMessage(error, 'save'); return data }
