import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import { Icon } from '../components/Icons'
import { acceptBooking, cancelBooking, completeBooking, getIncomingBookings, rejectBooking, startBooking } from '../services/bookingService'
import { ErrorState, LoadingState } from '../components/PageStates'

const labels = { REQUESTED: 'Requested', ACCEPTED: 'Accepted', REJECTED: 'Rejected', IN_PROGRESS: 'In progress', COMPLETED: 'Completed', CANCELLED: 'Cancelled' }

export default function BookingRequests() {
  const [bookings, setBookings] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; getIncomingBookings().then((data) => active && setBookings(data)).catch(() => active && setError('Unable to load bookings. Please try again.')).finally(() => active && setLoading(false)); return () => { active = false } }, [])
  const updateStatus = async (booking, action) => { try { const next = await action(booking); setBookings((current) => current.map((item) => item.id === booking.id ? { ...item, ...next } : item)) } catch { setError('Unable to complete this action. Please try again.') } }
  return <div className="site-page"><Navbar /><main className="bookings-page"><section className="booking-heading"><div><p className="eyebrow eyebrow-orange">Provider workspace</p><h1>Booking <em>Requests.</em></h1><p>Review incoming requests for machines or worker services you provide.</p></div></section>{loading ? <State text="Loading bookings..." /> : error ? <State text={error} error /> : bookings.length === 0 ? <State text="No booking requests yet." empty /> : <div className="booking-list">{bookings.map((booking) => <RequestRow key={booking.id} booking={booking} onAccept={() => updateStatus(booking, acceptBooking)} onReject={() => updateStatus(booking, rejectBooking)} onStart={() => updateStatus(booking, startBooking)} onComplete={() => updateStatus(booking, completeBooking)} onCancel={() => updateStatus(booking, cancelBooking)} />)}</div>}</main><Footer /></div>
}

function RequestRow({ booking, onAccept, onReject, onStart, onComplete, onCancel }) { const item = booking.worker || booking.machine || booking.tanker || booking.material; const isWorker = booking.item_type === 'WORKER'; const isTanker = booking.item_type === 'TANKER'; const isMaterial = booking.item_type === 'MATERIAL'; const requested = booking.status === 'REQUESTED'; const accepted = booking.status === 'ACCEPTED'; const inProgress = booking.status === 'IN_PROGRESS'; const title = isWorker ? item?.display_name : item?.title || item?.name; const type = isWorker ? item?.skill : isTanker ? 'Water tanker' : isMaterial ? item?.category : item?.machine_type; return <article className="booking-row request-row"><div className="booking-row-icon"><Icon name={isWorker ? 'users' : isTanker ? 'water' : isMaterial ? 'box' : 'user'} size={25} /></div><div className="booking-row-copy"><p className="eyebrow">{type || 'Provider request'}</p><h2>{title || (isWorker ? 'Worker request' : isTanker ? 'Tanker request' : isMaterial ? 'Material request' : 'Machine unavailable')}</h2><p><Icon name="compass" size={13} /> {[item?.city, item?.state].filter(Boolean).join(', ') || 'Location unavailable'}</p><p className="request-note">{booking.customer_note || 'No project note provided.'}</p></div><div className={`status-badge status-${booking.status.toLowerCase()}`}>{labels[booking.status] || booking.status}</div><div className="booking-row-meta"><span>{booking.start_date} to {booking.end_date} · Qty {booking.quantity}</span><strong>₹{Number(booking.total_price).toLocaleString('en-IN')}</strong>{requested && <div className="request-actions"><button type="button" className="button button-small" onClick={onAccept}>Accept</button><button type="button" className="button button-small button-ghost" onClick={onReject}>Reject</button></div>}{accepted && <div className="request-actions"><button type="button" className="button button-small" onClick={onStart}>Start work</button><button type="button" className="button button-small button-ghost" onClick={onCancel}>Cancel</button></div>}{inProgress && <div className="request-actions"><button type="button" className="button button-small" onClick={onComplete}>Complete</button><button type="button" className="button button-small button-ghost" onClick={onCancel}>Cancel</button></div>}<Link to={`/bookings/${booking.id}`} className="text-link text-link-dark">View details <Icon name="arrow" size={15} /></Link></div></article> }
function State({ text, error = false, empty = false }) { if (error) return <ErrorState onRetry={() => window.location.reload()} className="booking-state" />; if (!empty) return <LoadingState message={text} className="booking-state" />; return <div className="marketplace-state booking-state"><Icon name="briefcase" size={25} /><p>{text}</p><Link to="/machines" className="button">Browse machines <Icon name="arrow" size={17} /></Link></div> }
