import { localToday, inclusiveDays, estimateRental } from '../utils/booking'
import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import { Icon } from '../components/Icons'
import { useAuth } from '../context/AuthContext'
import { requestMaterialBooking } from '../services/bookingService'
import { getMaterial } from '../services/materialService'
import ProviderRatings from '../components/ProviderRatings'
import FavoriteButton from '../components/FavoriteButton'
import { ErrorState, LoadingState } from '../components/PageStates'
import MarketplaceImage from '../components/MarketplaceImage'
export default function MaterialDetails() { const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { isAuthenticated, profile } = useAuth(); const [material, setMaterial] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [notice, setNotice] = useState(''); useEffect(() => { let active = true; getMaterial(id).then((data) => active && setMaterial(data)).catch(() => active && setError('Unable to load material. Please try again.')).finally(() => active && setLoading(false)); return () => { active = false } }, [id]); const request = () => { if (!isAuthenticated) return navigate('/login', { state: { from: location.pathname } }); if (!profile || profile.role === 'admin') return setNotice('This account cannot request materials.'); if (material?.availability_status !== 'AVAILABLE' || Number(material?.quantity_available) <= 0) return setNotice('This material is not currently available.'); setNotice(''); setOpen(true) }; if (loading) return <Shell><State text="Loading materials..." /></Shell>; if (error || !material) return <Shell><State text={error || 'Material not found.'} error /></Shell>; return <Shell><Link to="/materials" className="text-link text-link-dark material-back"><Icon name="arrow" size={15} className="back-arrow" /> Back to materials</Link><section className="material-detail"><div className="material-detail-media"><MarketplaceImage src={material.image_url} alt={material.name} fallback={<Icon name="box" size={78} />} /></div><div className="material-detail-copy"><p className="eyebrow eyebrow-orange">{material.category}</p><h1>{material.name}</h1><p className="material-detail-location"><Icon name="compass" size={16} />{[material.city, material.state].filter(Boolean).join(', ')}</p><div className="material-detail-price"><strong>₹{Number(material.price).toLocaleString('en-IN')}</strong><span>/{material.unit}</span></div><div className="material-facts"><Fact label="Available quantity" value={material.quantity_available} /><Fact label="Availability" value={material.availability_status} /><Fact label="Location" value={material.city} /></div><p className="material-detail-description">{material.description || 'No description provided.'}</p>
<FavoriteButton itemType="MATERIAL" itemId={material.id} className="favorite-detail-button" /><ProviderRatings itemType="MATERIAL" itemId={material.id} />
<button type="button" className="button" onClick={request}>Request material <Icon name="arrow" size={17} /></button>{notice && <p className="machine-notice" role="status">{notice}</p>}{open && <MaterialRequestForm material={material} onCancel={() => setOpen(false)} onSuccess={() => { setOpen(false); setNotice('Material request sent successfully.') }} />}</div></section></Shell> }
function MaterialRequestForm({ material, onCancel, onSuccess }) { const today = localToday(); const [form, setForm] = useState({ startDate: today, endDate: today, quantity: 1, note: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const total = Number(material.price) * Number(form.quantity || 0); const submit = async (event) => { event.preventDefault(); setError(''); if (form.endDate < form.startDate || Number(form.quantity) <= 0 || Number(form.quantity) > Number(material.quantity_available)) return setError('Choose valid dates and an available quantity.'); setBusy(true); try { await requestMaterialBooking({ materialId: material.id, ...form }); onSuccess() } catch (submitError) { setError(submitError.message) } finally { setBusy(false) } }; return <div className="material-request-form"><p className="eyebrow eyebrow-orange">Request details</p><h2>Request this material</h2>{error && <p className="form-error" role="alert">{error}</p>}<form onSubmit={submit}><div className="booking-date-fields"><label className="form-label">Start date<input required type="date" min={today} value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></label><label className="form-label">End date<input required type="date" min={form.startDate} value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></label></div><label className="form-label">Quantity<input required type="number" min="1" step="0.01" max={material.quantity_available} value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} /></label><label className="form-label">Project note<textarea rows="3" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Add site context or requirements" /></label><div className="worker-estimate"><span>Estimated total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><div className="form-actions"><button type="button" className="button button-ghost" onClick={onCancel}>Cancel</button><button type="submit" className="button" disabled={busy}>{busy ? 'Sending material request...' : 'Send request'} <Icon name="arrow" size={17} /></button></div></form></div> }
function Fact({ label, value }) { return <div><small>{label}</small><strong>{value}</strong></div> }
function Shell({ children }) { return <div className="site-page"><Navbar /><main className="materials-page">{children}</main><Footer /></div> }
function State({ text, error = false }) { if (error) return <ErrorState onRetry={() => window.location.reload()} className="material-state" />; return <LoadingState message={text} className="material-state" /> }
