import { localToday, inclusiveDays, estimateRental } from '../utils/booking'
import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import { Icon } from '../components/Icons'
import { useAuth } from '../context/AuthContext'
import { requestTankerBooking } from '../services/bookingService'
import { getTanker } from '../services/tankerService'
import ProviderRatings from '../components/ProviderRatings'
import FavoriteButton from '../components/FavoriteButton'
import { ErrorState, LoadingState } from '../components/PageStates'

const labels = { AVAILABLE: 'Available', BOOKED: 'Booked', UNAVAILABLE: 'Unavailable' }
export default function TankerDetails() { const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { isAuthenticated, profile } = useAuth(); const [tanker, setTanker] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [notice, setNotice] = useState(''); useEffect(() => { let active = true; getTanker(id).then((data) => active && setTanker(data)).catch(() => active && setError('Unable to load tanker. Please try again.')).finally(() => active && setLoading(false)); return () => { active = false } }, [id]); const request = () => { if (!isAuthenticated) return navigate('/login', { state: { from: location.pathname } }); if (!profile || profile.role === 'admin') return setNotice('This account cannot request a tanker.'); if (tanker?.availability_status !== 'AVAILABLE' || tanker?.status !== 'ACTIVE') return setNotice('This tanker is not currently available.'); setNotice(''); setOpen(true) }; if (loading) return <Shell><State text="Loading tankers..." /></Shell>; if (error || !tanker) return <Shell><State text={error || 'Tanker not found.'} error /></Shell>; return <Shell><Link to="/tankers" className="text-link text-link-dark tanker-back"><Icon name="arrow" size={15} className="back-arrow" /> Back to tankers</Link><section className="tanker-detail"><div className="tanker-detail-art"><Icon name="water" size={76} /><span>{Number(tanker.capacity).toLocaleString('en-IN')} capacity</span></div><div className="tanker-detail-copy"><p className="eyebrow eyebrow-orange">Water tanker</p><h1>{tanker.title}</h1><p className="tanker-detail-location"><Icon name="compass" size={16} />{[tanker.city, tanker.state].filter(Boolean).join(', ')}</p><div className="tanker-detail-price"><strong>₹{Number(tanker.price).toLocaleString('en-IN')}</strong><span>{tanker.price_unit}</span></div><div className="tanker-facts"><Fact label="Capacity" value={tanker.capacity} /><Fact label="Availability" value={labels[tanker.availability_status] || tanker.availability_status} /><Fact label="Status" value={tanker.status} /></div><p className="tanker-detail-description">{tanker.description || 'No description provided.'}</p>
<FavoriteButton itemType="TANKER" itemId={tanker.id} className="favorite-detail-button" /><ProviderRatings itemType="TANKER" itemId={tanker.id} />
<button type="button" className="button" onClick={request}>Request tanker <Icon name="arrow" size={17} /></button>{notice && <p className="machine-notice" role="status">{notice}</p>}{open && <TankerRequestForm tanker={tanker} onCancel={() => setOpen(false)} onSuccess={() => { setOpen(false); setNotice('Tanker request sent successfully.') }} />}</div></section></Shell> }
function TankerRequestForm({ tanker, onCancel, onSuccess }) { const today = localToday(); const [form, setForm] = useState({ startDate: today, endDate: today, quantity: 1, note: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const days = form.endDate >= form.startDate ? inclusiveDays(form.startDate, form.endDate) : 0; const total = estimateRental(tanker.price, form.quantity || 0, tanker.price_unit, form.startDate, form.endDate); const submit = async (event) => { event.preventDefault(); setError(''); if (form.endDate < form.startDate || Number(form.quantity) <= 0) return setError('Choose valid dates and quantity.'); setBusy(true); try { await requestTankerBooking({ tankerId: tanker.id, ...form }); onSuccess() } catch (submitError) { setError(submitError.message) } finally { setBusy(false) } }; return <div className="tanker-request-form"><p className="eyebrow eyebrow-orange">Request details</p><h2>Request this tanker</h2>{error && <p className="form-error" role="alert">{error}</p>}<form onSubmit={submit}><div className="booking-date-fields"><label className="form-label">Start date<input required type="date" min={today} value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></label><label className="form-label">End date<input required type="date" min={form.startDate} value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></label></div><label className="form-label">Quantity<input required type="number" min="1" step="1" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} /></label><label className="form-label">Project note<textarea rows="3" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Add site context or requirements" /></label><div className="worker-estimate"><span>Estimated request total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><div className="form-actions"><button type="button" className="button button-ghost" onClick={onCancel}>Cancel</button><button type="submit" className="button" disabled={busy}>{busy ? 'Sending tanker request...' : 'Send request'} <Icon name="arrow" size={17} /></button></div></form></div> }
function Fact({ label, value }) { return <div><small>{label}</small><strong>{value}</strong></div> }
function Shell({ children }) { return <div className="site-page"><Navbar /><main className="tankers-page">{children}</main><Footer /></div> }
function State({ text, error = false }) { if (error) return <ErrorState onRetry={() => window.location.reload()} className="tanker-state" />; return <LoadingState message={text} className="tanker-state" /> }
